// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTransform(arg1, arg2) {
  return window['go']['main']['App']['ApplyTransform'](arg1, arg2);
}

export function CopyTextToClipboard(arg1) {
  return window['go']['main']['App']['CopyTextToClipboard'](arg1);
}

export function DeleteAllItems() {
  return window['go']['main']['App']['DeleteAllItems']();
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function DetectContent(arg1) {
  return window['go']['main']['App']['DetectContent'](arg1);
}

export function ExportData(arg1) {
  return window['go']['main']['App']['ExportData'](arg1);
}

export function GetClipboardItem(arg1) {
  return window['go']['main']['App']['GetClipboardItem'](arg1);
}

export function GetClipboardItems(arg1, arg2) {
  return window['go']['main']['App']['GetClipboardItems'](arg1, arg2);
}

export function GetClipboardItemsByTag(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClipboardItemsByTag'](arg1, arg2, arg3);
}

export function GetClipboardItemsByType(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetClipboardItemsByType'](arg1, arg2, arg3);
}

export function GetItemCount() {
  return window['go']['main']['App']['GetItemCount']();
}

export function GetItemData(arg1) {
  return window['go']['main']['App']['GetItemData'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetTags() {
  return window['go']['main']['App']['GetTags']();
}

export function GetTransforms() {
  return window['go']['main']['App']['GetTransforms']();
}

export function ImportData(arg1) {
  return window['go']['main']['App']['ImportData'](arg1);
}

export function IsPaused() {
  return window['go']['main']['App']['IsPaused']();
}

export function IsSecurityEnabled() {
  return window['go']['main']['App']['IsSecurityEnabled']();
}

export function PasteItem(arg1) {
  return window['go']['main']['App']['PasteItem'](arg1);
}

export function PasteItemAsPlainText(arg1) {
  return window['go']['main']['App']['PasteItemAsPlainText'](arg1);
}

export function SearchClipboard(arg1) {
  return window['go']['main']['App']['SearchClipboard'](arg1);
}

export function SetPaused(arg1) {
  return window['go']['main']['App']['SetPaused'](arg1);
}

export function SetSecurityEnabled(arg1) {
  return window['go']['main']['App']['SetSecurityEnabled'](arg1);
}

export function TogglePanel() {
  return window['go']['main']['App']['TogglePanel']();
}

export function TogglePin(arg1) {
  return window['go']['main']['App']['TogglePin'](arg1);
}

export function UpdateCustomTitle(arg1, arg2) {
  return window['go']['main']['App']['UpdateCustomTitle'](arg1, arg2);
}

export function UpdateTagID(arg1, arg2) {
  return window['go']['main']['App']['UpdateTagID'](arg1, arg2);
}
