// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyTransform(arg1:string,arg2:string):Promise<string>;

export function CopyTextToClipboard(arg1:string):Promise<void>;

export function DeleteAllItems():Promise<void>;

export function DeleteItem(arg1:number):Promise<void>;

export function DetectContent(arg1:string):Promise<Record<string, any>>;

export function ExportData(arg1:string):Promise<void>;

export function GetClipboardItem(arg1:number):Promise<Record<string, any>>;

export function GetClipboardItems(arg1:number,arg2:number):Promise<Array<Record<string, any>>>;

export function GetClipboardItemsByTag(arg1:number,arg2:number,arg3:number):Promise<Array<Record<string, any>>>;

export function GetClipboardItemsByType(arg1:string,arg2:number,arg3:number):Promise<Array<Record<string, any>>>;

export function GetItemCount():Promise<number>;

export function GetItemData(arg1:number):Promise<string>;

export function GetSystemInfo():Promise<Record<string, any>>;

export function GetTags():Promise<Array<Record<string, any>>>;

export function GetTransforms():Promise<Array<Record<string, any>>>;

export function ImportData(arg1:string):Promise<void>;

export function IsPaused():Promise<boolean>;

export function IsSecurityEnabled():Promise<boolean>;

export function PasteItem(arg1:number):Promise<void>;

export function PasteItemAsPlainText(arg1:number):Promise<void>;

export function SearchClipboard(arg1:string):Promise<Array<Record<string, any>>>;

export function SetPaused(arg1:boolean):Promise<void>;

export function SetSecurityEnabled(arg1:boolean):Promise<void>;

export function TogglePanel():Promise<void>;

export function TogglePin(arg1:number):Promise<void>;

export function UpdateCustomTitle(arg1:number,arg2:string):Promise<void>;

export function UpdateTagID(arg1:number,arg2:number):Promise<void>;
